apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260520-155110-q4qgchs1ushw-service
spec:
  selector:
    app: enterprise-system-20260520-155110-q4qgchs1ushw
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
